# Stage 1: Build the Go binary
FROM golang:alpine AS build

# Set the working directory inside the container
WORKDIR /app
COPY . .

# Build the Go application
RUN go build -o main .

# Stage 2: Create a smaller image to run the application
FROM alpine:3.14

# Copy the built Go binary from the build stage
COPY --from=build /app/main /app/

# Expose port 8080 to be able to access the app
EXPOSE 8080

# Set the command to run the application
CMD ["/app/main"]
